### ISSUE TITLE
2장 카프카 브로커 설치 오류..

### ISSUE THREAD

**Issue by youjin827** [bjpublic/apache-kafka-with-java#1]
<img width="1074" alt="스크린샷 2021-06-03 오후 5 57 57" src="https://user-images.githubusercontent.com/50617838/120617603-3d25f100-c495-11eb-94c2-8e9eb5ec3cf4.png">

실행이 안됩니다... 이 오류 아시면 도와주세요 ㅠㅠ 너무 힘드네요...

**Comment by AndersonChoi** [comment]
안녕하세요 @youjin827 님, 
상기 오류는 로컬환경에서 ec2의 카프카에 접속하지 못하여 발생하는 현상입니다. 아래와 같은 절차를 따라해보시면서 접속 가능여부를 확인해보세요.

1. ec2에 접속하여 jps 명령어로 카프카, 주키퍼 실행되고 있는지 확인
2. 카프카 로그(logs/server.log) 확인하여 브로커에 에러 로그 있는지 확인
3. ec2 인스턴스가 public ip를 가지고 있는지 확인
4. 해당 인스턴스가 외부와 연결되어 있는지 보안 그룹 확인
