### ISSUE TITLE
주키퍼 쉘 명령어 실행 오류 

### ISSUE THREAD

**Issue by youjin827** [bjpublic/apache-kafka-with-java#3]
<img width="736" alt="스크린샷 2021-06-20 오후 6 29 06" src="https://user-images.githubusercontent.com/50617838/122668931-901dd900-d1f5-11eb-9197-c002b5386b75.png">

swap 메모리 부족이 원인인지 , 다른 메모리 부족이 원인인지 잘 모르겠습니다. 
혹시 swap 메모리 부족이 원인이라면, 
swap 폴더를 따로 만들어 swap 메모리를 2G 정도 설정해주면 자동으로 설정이 되는지도 궁금합니다..

**Comment by AndersonChoi** [comment]
@youjin827 님, 스크린샷에 따르면 쉘을 실행하기 위한 메모리가 부족한 것으로 보입니다. 실행하시는 쉘 스크립트(zookeeper-shell.sh)를 ec2에서 실행하지 마시고 로컬에서 실행하셔서 연결해보세요~
