### ISSUE TITLE
주키퍼 타임아웃 에러

### ISSUE THREAD

**Issue by youjin827** [bjpublic/apache-kafka-with-java#4]
<img width="757" alt="스크린샷 2021-06-25 오후 2 30 24" src="https://user-images.githubusercontent.com/50617838/123374763-9ed40980-d5c2-11eb-980a-39d6f2102582.png">

 intelliJ 에서 simple-kafka-producer 파일을 만들고 내용을 넣은 후,  로컬에서 토픽을 생성하였는데 'Broker may not be available.' 에러가 나서 
1. 인스턴스에서 jps -m 를 실행해보니 Kafka config/server.properties 가 실행이 끊겨있었습니다. 
2.  다시 실행시키고 jps 로 확인해봐도 잠시 떠있을 뿐 다시 연결이 끊깁니다. 
3. log를 확인해보니 18000ms 세션이 만료되었다고 떴습니다.

+ rm -rf /tmp/kafka-logs 를 써 해결이 되었습니다.!! 하지만 원인은 알 수 가 없네요 ㅠ ㅎㅎ 혹시 이런 상황의 원인을 알고 계실까요..? 다음 카프카 실행 시 또 이런 에러가 날까봐 두렵네요 ㅎㅎ

**Comment by AndersonChoi** [comment]
@youjin827 님, 해당 에러는 /tmp 이하 폴더에 데이터가 잘못 생성되어 있어서 그런것으로 보입니다. 추후 브로커 실행시 /tmp 가 아닌 다른 디렉토리를 지정하신다면 유사 에러가 나지 않을 것입니다.
