### ISSUE TITLE
안녕하세요.

### ISSUE THREAD

**Issue by lllilllilllilili** [bjpublic/apache-kafka-with-java#5]
[마스터에 올려주신 소스코드](https://github.com/bjpublic/apache-kafka-with-java/blob/master/Chapter3/3.4.2%20kafka-consumer/kafka-consumer-rebalance-listener/src/main/java/com/example/ConsumerWithRebalanceListener.java) 가 책 내용 중 예제 코드 kafka-consumer-rebalance-listener (109페이지) 랑 조금 다른거 같은데 올려둔 소스코드로 공부하면 될까요?
저자님 새해복 많이 받으세요. 🙇🏻‍♂️

**Comment by AndersonChoi** [comment]
안녕하세요. RebalanceListener를 java class로 추출했을 뿐, 동일한 로직이므로 둘 다 참고하셔도 됩니다!

**Comment by ryanproback** [comment]
안녕하세요. 좋은 책 작성해주셔서 감사합니다. 덕분에 카프카에 대해 잘 학습하고 있습니다.

여기 올려주신 kafka-consumer-rebalance-listener 코드와 109 페이지의 코드가 다른 것 같습니다.
말씀해주신 RebalanceListener 를 분리하신 것 외에도요.

1. 책의 코드에선 poll()로 불러온 records 를 가지고 for each loop를 탈 때
commitSync()를 호출하고 있으나, 여기 코드에선 로그만 찍습니다.
2. 책의 코드에선 RebalanceListener.onPartitionsRevoked() 호출 시
commitSync()를 호출하도록 구현하셨으나, 여기 코드에선 역시 로그만 찍습니다.

추가로 제가 이 이슈를 찾아온 배경에 대해 말씀드리면,
109페이지 코드에 일부 빠진 내용이 있어서 입니다.
(github 코드에는 완전한 내용이 있을 것 같아 찾아왔지만, 위 언급과 같이 109 페이지 코드와 내용이 달랐습니다.)
`Map<TopicPartion, OffsetAndMetadata>` 타입의 인스턴스를 생성하여  
`commitSync` 메서드의 파라미터로 넘겨야 하나,
인스턴스 생성 (+ 변수 선언) 라인이 빠져있습니다.

수정이 되면 좋을 것 같은데, 직접 수정해주셔도 좋고, 괜찮으시다면 제가 PR을 올리겠습니다.
